name: Cilium Conn Disrupt Check
description: Check cilium connection disruption status

inputs:
  job-name:
    required: true
    description: 'Job name used in Cilium CLI outputs'
  extra-connectivity-test-flags:
    required: false
    description: 'Cilium CLI connectivity tests extra flags'
  full-test:
    required: false
    default: 'false'
    description: 'Run full connectivity test suite'

runs:
  using: composite
  steps:
    - name: Perform Conn Disrupt Test
      shell: bash
      run: |
        TEST_ARG="no-interrupted-connections"
        if [[ "${{ inputs.full-test }}" == "true" ]]; then
          TEST_ARG=""
        fi
        ./cilium-cli connectivity test --include-unsafe-tests --collect-sysdump-on-failure \
          --include-conn-disrupt-test \
          --flush-ct \
          --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m \
          --sysdump-output-filename "cilium-sysdump-${{ inputs.job-name }}-<ts>" \
          --junit-file "cilium-junits/${{ inputs.job-name }}.xml" \
          ${{ inputs.extra-connectivity-test-flags }} \
          --junit-property github_job_step="Run conn disrupt tests (${{ inputs.job-name }})" \
          --test "$TEST_ARG" \
          --expected-xfrm-errors "+inbound_no_state"
